import cluster

diff --git a/Jenkinsfile.eks b/Jenkinsfile.eks
--- a/Jenkinsfile.eks
+++ b/Jenkinsfile.eks
@@ -84,12 +84,12 @@ stages {
 		    echo "Check AWS clusters:"
 		    aws eks list-clusters --region ${AWS_REGION} --no-cli-pager
 
-		    echo "Check specific cluster:"
-		    aws eks describe-cluster --name todo-eks --region ${AWS_REGION} --no-cli-pager || echo "Cluster not found"
-		    aws eks describe-cluster \
-		      --name todo-eks \
-		      --region eu-north-1 \
-		      --query "cluster.{version:version,role:roleArn,encryption:encryptionConfig}"
+		    #echo "Check specific cluster:"
+		    #aws eks describe-cluster --name todo-eks --region ${AWS_REGION} --no-cli-pager || echo "Cluster not found"
+		    #aws eks describe-cluster \
+		    #  --name todo-eks \
+		    #  --region eu-north-1 \
+		    #  --query "cluster.{version:version,role:roleArn,encryption:encryptionConfig}"
 		    echo "====== DEBUG END ======"
 
 
